apiVersion: v1
kind: Service
metadata:
  name: doctor-app-service
spec:
  selector:
    app: doctor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
